/// Flutter icons Invite
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Invite
///      fonts:
///       - asset: fonts/Invite.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Invite {
  Invite._();

  static const _kFontFam = 'Invite';
  static const String _kFontPkg = null;

  static const IconData final_rounded =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chip =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
